### ISSUE TITLE
GET Option

### ISSUE THREAD

**Issue by ashish-billore** [dougbtv/whereabouts#52]
**First**: This is really not an issue, it's just a query and suggestion, so please feel free to resolve it as appropriately.

**Query**:
- I wish to query the current IPAM allocation status. Basically, I want to get a list of:

_type IPReservation struct {
	IP          net.IP `json:"ip"`
	ContainerID string `json:"id"`
}_

This could be very useful in several cases:
1. I want to report current allocations, for example in grafana dashboard.
2. If I see some errors such as no more free IPs, I want to know if there is any IP leaks due to certain race conditions during abnormal updates/crashes on multiple concurrent ADD/DEL requests.
3. logging etc.
-----

For this, I tried to implement a function in storage.go for this like:

_// ListAllReservedIP returns a List of all ip reservations from a storage perspective
func ListAllReservedIP(ipamConf types.IPAMConfig) ([]types.IPReservation, error) {
...
}_

and then add GET option in whereabouts.go

I understand, this is not as per the CNI specs and hence there is no supported Result type usable for this in:
"github.com/containernetworking/cni/pkg/types"

So, I am looking for recommended ways to get this kind of data for above purposes. 
Any suggestions or pointers are welcome! Thanks!

**Comment by ashish-billore** [comment]
A Note: This is different than what is mentioned here:
https://github.com/dougbtv/whereabouts/issues/3

**Comment by dougbtv** [comment]
@ashish-billore interesting perspective on the usage for GET. I'm with you, from a CNI spec perspective, it's not exactly what you'd return.

That being said, I agree that giving visibility of this data in a way that's machine legible to then make it human legible (e.g. via grafana dashboard!) is very useful.

I'm not... exactly sure on the right way to expose this. Hrmmm....

Here's a possibility though, we could extend Whereabouts to make it so that you could run it at a command prompt so that you could pull up this data, so you could execute it externally, and give it k8s credentials so it could query the API, and return information for you to use in grafana (for example), say something like...

```
$ ./whereabouts --kubeconfig=/path/to/kubeconfig --rangeinfo=192.168.1.0/24
{ ips_available: 5, ips_used: 250, ips_allocated: [...]}
```

I'll keep thinking on this, also open to other proposals for how to expose it, too.

re: #3 -- I'd love a PR against it if you're up to making a proposal there, too!

**Comment by ashish-billore** [comment]
@dougbtv thanks for your perspective and insight into possibility of GET option.
For now, I am inclined to go with the approach you have suggested above (invoke externally whereabouts executable), so will try it out. Thanks much!

**Comment by ashish-billore** [comment]
@dougbtv I am closing this issue as invoking the standalone binary to get info satisfies my requirement for now, thanks!

**Comment by crandles** [comment]
FYI, this information is accessible via kubectl: `kubectl get ippool ...` if you are willing to work with the existing CRD format.
